# Generated by Django 3.1.5 on 2021-02-15 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('afternoon', 'Απόγευμα'), ('morning', 'Πρωί')], max_length=50)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('weekday', models.CharField(choices=[('monday', 'Δευτέρα'), ('tuesday', 'Τρίτη'), ('wednesday', 'Τετάρτη')], max_length=30, null=True)),
                ('entrydate', models.DateField(default='2021-02-15', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Κωδικός Τμήματος')),
                ('specialty', models.CharField(max_length=30, verbose_name='Όνομα Ειδικότητας')),
                ('duration', models.IntegerField(verbose_name='Διάρκεια')),
                ('price', models.IntegerField(verbose_name='Ενδεικτική Τιμή')),
                ('entrydate', models.DateField(default='2021-02-15', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Όνομα')),
                ('lastname', models.CharField(max_length=50, verbose_name='Επώνυμο')),
                ('fathersname', models.CharField(max_length=50, verbose_name='Πατρώνυμο')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Ημερ. Γεν')),
                ('afm', models.CharField(max_length=30, verbose_name='ΑΦΜ')),
                ('sex', models.CharField(choices=[('male', 'Άνδρας'), ('female', 'Γυναίκα')], max_length=7, verbose_name='Φύλο')),
                ('doy', models.CharField(choices=[('chalkidiki', 'ΧΑΛΚΙΔΙΚΗ'), ('loc2', 'll')], max_length=30, verbose_name='ΔΟΥ')),
                ('adt', models.CharField(max_length=30, verbose_name='Α.Δ.Τ./ Α.Δ')),
                ('location', models.CharField(max_length=30, verbose_name='Πόλη')),
                ('publishfile', models.CharField(max_length=30, verbose_name='Αρχ. Έκδοσης')),
                ('address', models.CharField(max_length=30, verbose_name='Διεύθυνση')),
                ('tk', models.CharField(max_length=30, verbose_name='Τ.Κ.')),
                ('prefecture', models.CharField(choices=[('chalkidiki', 'ΧΑΛΚΙΔΙΚΗ'), ('loc2', 'll')], max_length=30, verbose_name='Νομός')),
                ('cellphone', models.CharField(max_length=30, verbose_name='Κινητό')),
                ('phonenumber', models.CharField(max_length=30, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('profession', models.CharField(max_length=30, verbose_name='Επάγγελμα')),
                ('entrydate', models.DateField(default='2021-02-15', verbose_name='Ημερομηνία Καταχώρησης')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=30, verbose_name='Επώνυμο')),
                ('firstname', models.CharField(max_length=30, verbose_name='Όνομα')),
                ('fathersname', models.CharField(max_length=30, verbose_name='πατρώνυμο')),
                ('mothersname', models.CharField(max_length=50, null=True, verbose_name='Μητρώνυμο')),
                ('afm', models.CharField(max_length=30, verbose_name='ΑΦΜ')),
                ('adt', models.CharField(max_length=30, verbose_name='ΑΔΤ')),
                ('phonenumber', models.CharField(blank=True, max_length=30, null=True, verbose_name='Τηλέφωνο')),
                ('cellphone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Κινητό')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('location', models.CharField(max_length=30, null=True, verbose_name='Τοποθεσία')),
                ('price', models.IntegerField(verbose_name='Τιμή')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Έκπτωση')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Γέννησης')),
                ('sex', models.CharField(choices=[('male', 'Άνδρας'), ('female', 'Γυναίκα')], max_length=7, null=True, verbose_name='Φύλο')),
                ('installments', models.IntegerField(blank=True, null=True)),
                ('studentImage', models.ImageField(blank=True, null=True, upload_to='student_images', verbose_name='Φωτογραφία')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Username')),
                ('entrydate', models.DateField(default='2021-02-15', null=True)),
                ('specialty', models.ManyToManyField(to='students.Specialty', verbose_name='Ειδικότητα')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('paid', models.BooleanField()),
                ('paymentdate', models.DateField(blank=True, null=True)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cash_register.receipt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theorygrade', models.IntegerField()),
                ('labgrade', models.IntegerField()),
                ('semester', models.CharField(choices=[('firstsemester', 'Α'), ('secondsemester', 'Β'), ('thirdsemester', 'Γ')], max_length=14)),
                ('schoolyear', models.CharField(choices=[('previous_school_year', '2020-2021'), ('current_school_year', '2021-2022')], max_length=20)),
                ('remarks', models.TextField()),
                ('entrydate', models.DateField(default='2021-02-15')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.specialty')),
            ],
        ),
    ]
