# Generated by Django 3.1.5 on 2021-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=30)),
                ('firstnames', models.CharField(max_length=30)),
                ('fathersname', models.CharField(max_length=30)),
                ('mothersname', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('afm', models.CharField(max_length=35)),
                ('doy', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=30)),
                ('adt', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('tk', models.CharField(max_length=10)),
                ('prefecture', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=30)),
                ('cellphone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('educationlevel', models.CharField(max_length=30)),
                ('companyname', models.CharField(max_length=30)),
                ('companyactivity', models.CharField(max_length=50)),
                ('employees', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
