# Generated by Django 3.1.5 on 2021-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=35)),
                ('fathersname', models.CharField(max_length=35)),
                ('gender', models.CharField(choices=[('male', 'Άνδρας'), ('female', 'Γυναίκα')], max_length=20)),
                ('birthdate', models.DateField()),
                ('region', models.CharField(choices=[('halkidki', 'halkidikis'), ('argolida', 'argolidas')], max_length=20, verbose_name='Περιφέρεια')),
                ('municipality', models.CharField(choices=[], max_length=20, verbose_name='Δήμος')),
                ('specificregion', models.CharField(max_length=20, verbose_name='Περιοχή/Πόλη/Χωριό')),
                ('amka', models.CharField(max_length=40)),
                ('afm', models.CharField(max_length=40)),
                ('doy', models.CharField(choices=[], max_length=30, verbose_name='ΔΟΥ')),
                ('adt', models.CharField(max_length=40)),
                ('phonenumber', models.CharField(max_length=35)),
                ('cellphone', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('schoolinglevel', models.CharField(max_length=35)),
                ('book', models.BooleanField()),
                ('price', models.IntegerField(default=25)),
                ('notes', models.TextField()),
            ],
        ),
    ]
