# Generated by Django 3.1.5 on 2021-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountable', models.CharField(default='Millennium IT Department', max_length=30, verbose_name='Ονοματεπώνυμο Υπεύθυνου')),
                ('recipient', models.CharField(max_length=30, verbose_name='Ονοματεπώνυμο εισπράκτωρα')),
                ('reason', models.TextField(verbose_name='Αιτιολογία')),
                ('amount', models.IntegerField(verbose_name='Ποσό')),
                ('category_a', models.DateField(choices=[('staffpaychecks', 'ΑΜΟΙΒΕΣ & ΕΞΟΔΑ ΠΡΟΣΩΠΙΚΟΥ'), ('thirdpartypaychecks', 'ΑΜΟΙΒΕΣ & ΕΞΟΔΑ ΤΡΙΤΩΝ'), ('materials', 'ΑΝΑΛΩΣΙΜΑ ΥΛΙΚΑ'), ('expenses', 'ΔΙΑΦΟΡΑ ΕΞΟΔΑ'), ('cashshortage', 'ΕΛΛΕΙΜΑ ΤΑΜΕΙΟΥ'), ('equipment', 'ΕΠΙΠΛΑ ΚΑΙ ΛΟΙΠΟΣ ΕΞΟΠΛΙΣΜΟΣ'), ('machinesequipment', 'ΜΗΧΑΝΗΜΑΤΑ'), ('thirdpartyexpenses', 'ΠΑΡΟΧΕΣ ΤΡΙΤΩΝ')], null=True, verbose_name='Κατηγορία Α')),
                ('category_b', models.DateField(choices=[('test', 'test'), ('test2', 'test2')], null=True, verbose_name='Κατηγορία Β')),
                ('category_c', models.DateField(choices=[('test', 'test'), ('test2', 'test2')], null=True, verbose_name='Κατηγορία Γ')),
                ('paymentmethod', models.CharField(choices=[('cash', 'ΜΕΤΡΗΤΑ'), ('bankdeposit', 'ΚΑΤΑΘΕΣΗ ΣΤΗ ΤΡΑΠΕΖΑ'), ('card', 'ΜΕΣΩ ΚΑΡΤΑΣ'), ('epay', 'ΗΛΕΚΤΡΟΝΙΚΗ ΠΛΗΡΩΜΗ')], max_length=30, verbose_name='Μέθοδος Πληρωμής')),
                ('type', models.CharField(choices=[('receipt', 'ΑΠΟΔΕΙΞΗ'), ('invoice', 'ΤΙΜΟΛΟΓΙΟ')], max_length=30, verbose_name='Είδος')),
                ('paymentway', models.CharField(choices=[('immediate', 'ΑΜΕΣΗ ΕΞΟΦΛΗΣΗ'), ('oncredit', 'ΕΠΙ ΠΙΣΤΩΣΕΙ')], max_length=30, verbose_name='Τρόπος Πληρωμής')),
                ('entrydate', models.DateField(default='2021-02-15', verbose_name='Ημερομηνία')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(default='Millennium IT Department', max_length=25, verbose_name='Ονοματεπώνυμο εισπράκτορα')),
                ('client', models.CharField(max_length=25, verbose_name='Πελάτης')),
                ('reason', models.TextField(verbose_name='Αιτιολογία')),
                ('amount', models.IntegerField(verbose_name='Ποσό')),
                ('paymentmethod', models.CharField(choices=[('cash', 'ΜΕΤΡΗΤΑ'), ('deposit', 'ΚΑΤΑΘΕΣΗ ΣΤΗ ΤΡΑΠΕΖΑ'), ('card', 'ΜΕΣΩ ΚΑΡΤΑΣ'), ('check', 'ΕΠΙΤΑΓΗ')], max_length=30, verbose_name='Μέθοδος Πληρωμής')),
                ('paymanetway', models.CharField(choices=[('immediate', 'ΑΜΕΣΗ ΕΞΟΦΛΗΣΗ'), ('oncredit', 'ΕΠΙ ΠΙΣΤΩΣΕΙ')], max_length=30, verbose_name='Τρόπος Πληρωμής')),
                ('entrydate', models.DateField(default='2021-02-15', verbose_name='Ημερομηνία')),
            ],
        ),
    ]
