# Generated by Django 3.1.5 on 2021-02-15 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='Όνομα')),
                ('lastname', models.CharField(max_length=30, verbose_name='Επώνυμο')),
                ('phonenumber', models.CharField(max_length=30, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('entrydate', models.DateField(default='2021-02-15', null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(null=True)),
                ('date', models.DateField(verbose_name='2021-02-15')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('wage_per_hour', models.FloatField()),
                ('total_hours', models.IntegerField()),
                ('total_wage', models.FloatField(null=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.specialty')),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='2021-02-15')),
                ('attendance', models.BooleanField()),
                ('preparation', models.FloatField()),
                ('performance', models.FloatField()),
                ('behaviour', models.FloatField()),
                ('cooperation', models.FloatField()),
                ('averagegrade', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
            ],
        ),
    ]
