# Generated by Django 3.1.5 on 2021-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('brandname', models.CharField(max_length=40)),
                ('afm', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=35)),
                ('seller', models.CharField(max_length=40)),
                ('cost', models.IntegerField()),
                ('entrydate', models.DateField()),
            ],
        ),
    ]
