# Generated by Django 3.1.5 on 2021-02-15 12:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspaService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, verbose_name='Υπηρεσία')),
                ('entrydate', models.DateField(default='2021-02-15', verbose_name='Ημερομηνία Καταχώρησης')),
            ],
        ),
        migrations.CreateModel(
            name='EspaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubsidizedBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40, verbose_name='Όνομα')),
                ('lastname', models.CharField(max_length=40, verbose_name='Επώνυμο')),
                ('companytype', models.CharField(max_length=40, verbose_name='Τύπος Επιχείρησης')),
                ('companyname', models.CharField(max_length=40, verbose_name='Επωνυμία')),
                ('location', models.CharField(max_length=40, verbose_name='Τοποθεσία')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Σχόλια')),
                ('phonenumber', models.CharField(max_length=40, verbose_name='Τηλέφωνο')),
                ('cellphone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Κινητό')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Εγκρίθηκε')),
                ('entrydate', models.DateField(default='2021-02-15', verbose_name='Ημερομηνία Καταχώρησης')),
                ('espauser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='espa.espauser')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Συστάθηκε Από')),
                ('services', models.ManyToManyField(to='espa.EspaService', verbose_name='Υπηρεσίες')),
            ],
        ),
        migrations.CreateModel(
            name='InterestedBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40, verbose_name='Όνομα')),
                ('lastname', models.CharField(max_length=40, verbose_name='Επώνυμο')),
                ('companytype', models.CharField(max_length=40, verbose_name='Τύπος Επιχείρησης')),
                ('companyname', models.CharField(max_length=40, verbose_name='Επωνυμία')),
                ('location', models.CharField(max_length=40, verbose_name='Τοποθεσία')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Σχόλια')),
                ('phonenumber', models.CharField(blank=True, max_length=40, null=True, verbose_name='Τηλέφωνο')),
                ('cellphone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Κινητό')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('entrydate', models.DateField(default='2021-02-15', verbose_name='Ημερομηνία Καταχώρησης')),
                ('referrer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Συστάθηκε Από')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='espa_documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Αρχείο')),
                ('inspected', models.BooleanField(default=False, verbose_name='Επιθεωρήθηκε')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Σχόλια')),
                ('entrydate', models.DateField(default='2021-02-15')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espa.subsidizedbusiness')),
            ],
        ),
    ]
